const items = [
  { txt: "Hair Band" },
  { txt: "Chess Piece" },
  { txt: "Pot Luck White Cube" },
  { txt: "Domino" },
  { txt: "Dice" },
  { txt: "Glass Pebble" },
  { txt: "Key Ring" },
  { txt: "Button" },
  { txt: "Tiddlywink" },
  { txt: "Lucky Clover", bg: "green", col: "white" },
  { txt: "Pot Luck Red Cube" },
  { txt: "Toy Car" },
  { txt: "Poker Chip" },
  { txt: "Golf Tee" },
  { txt: "Plectrum" },
  { txt: "Wheel" },
  { txt: "Ping Pong Ball" },
  { txt: "Letter Tile" },
  { txt: "Wooden Pawn" },
  { txt: "Wrong Handed", bg: "red", col: "white", modifier: "spin" },
  { txt: "Pot Luck Blue Cube" },
  { txt: "Pig" },
  { txt: "Toy Brick" },
  { txt: "Wooden Bead" },
  { txt: "Draught Piece" },
  { txt: "Bouncy Ball" },
  { txt: "Hotel" },
  { txt: "Elastic Band" },
  { txt: "Marble" },
  { txt: "Cork" },
  { txt: "Find Your Feet", bg: "teal", col: "white" }
];

export default items;
